### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by shanel262** [senecajs/seneca-redis-store#19]
The travis build is failing when using both Seneca@1.x and 2.x with all supported versions of Node (.10, .12, 4, 5  and 6) #18 https://travis-ci.org/senecajs/seneca-redis-store/builds/128865266

**Comment by mihaidma** [comment]
tests are passing. The only issue with them is that redis doesn't work with latest 1.1.0 store tests. Opened an issue for that: https://github.com/senecajs/seneca-redis-store/issues/22
